name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      
      - name: compile...
        run: |
            npm ci
            npm run build
            ls
      - name: Push on Linkit/gh-pages
        uses: Override-6/Linkit@gh-pages
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '/'
          destination-github-username: 'Override6'
          destination-repository-name: 'Linkit'
          user-email: 'maximebatista18@gmail.com'
          commit-message: commit $GITHUB_REF pls work
          target-branch: gh-pages
