name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: clone Override-6/Linkit/gh-pages
        run: |
          cd /home/runner/work/
          git clone https://user:@github.com/Override-6/Linkit
          cd /home/runner/work/Linkit
          pwd
          git checkout gh-pages
          ls
      - name: compile...
        run: |
            npm ci
            npm run build
            cp -R /home/runner/work/Linkit-Wiki/Linkit-Wiki/build/* /home/runner/work/Linkit/

      - name: make commit
        run: |
          cd /home/runner/work/Linkit
          git config --global user.email "maximebatista18@gmail.com"
          git config --global user.name "Override-6 [bot]"
          git add .
          git commit --allow-empty -m "auto commit"
          git push https://Override-6:$GITHUB_TOKEN@github.com/Override-6/Linkit gh-pages --force
